//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crudprueba.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPuestos
    {
        public Nullable<int> EmpresaID { get; set; }
        public int PuestoID { get; set; }
        public string PuestoCodigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<System.DateTime> FechaDeBaja { get; set; }
    
        public virtual TblEmpresas TblEmpresas { get; set; }
    }
}
